import = [
  # "${XDG_DATA_HOME}/repos/github.com/alacritty/alacritty-theme/themes/nord.toml"
  "~/.local/share/repos/github.com/alacritty/alacritty-theme/themes/nord.toml",
  # "${XDG_CONFIG_HOME}/alacritty/customize.yml",
  # "customize.yml",
  "~/.dotfiles/alacritty/customize.toml",
]
