[[snippets]]
  description = "Replace \"hoge\" with \"fuga\" text files recursively under current directory"
  command = "find ./ -type f -name *.txt -exec gsed -i -e 's/hoge/fuga/g' {} \\;"
  output = ""

[[snippets]]
  description = "Open file on git server via vim"
  command = "!git brws %"
  output = ""

[[snippets]]
  description = "Generate private key (default size: 2048 so far)"
  command = "openssl genrsa > private-key.pem"
  output = ""

[[snippets]]
  description = "Generate public key with given private key"
  command = "openssl rsa -pubout < private-key.pem > public-key.pem"
  output = ""

[[snippets]]
  description = "Generate CSR (Certificate Signing Request) with given server private key"
  command = "openssl req -new -key server.key > server.csr"
  output = ""

[[snippets]]
  description = "Generate CRT (Self-signed certificate) with given server private key and self-signed CSR"
  command = "openssl x509 -req -signkey server.key < server.csr > server.crt"
  output = ""

[[snippets]]
  description = "Checkout remote master anyway"
  command = "git reset --hard origin/master"
  output = ""

[[snippets]]
  description = "Generate uuid with lower cases"
  command = "uuidgen | tr \"[:upper:]\" \"[:lower:]\""
  output = ""

[[snippets]]
  description = "Generate random hex with 4 bytes"
  command = "openssl rand -hex 4"
  output = ""

[[snippets]]
  description = "List open files listen to 8080 port"
  command = "lsof -n -P -i :8080"
  output = ""

[[snippets]]
  description = "Replace \"deprecated\" with \"new\" for all files in the current directory"
  command = "find ./ -type f -exec sed -i -e 's/deprecated/new/g' {} \\;"
  output = ""
