[[snippets]]
  description = "Open file on git server via vim"
  command = "!git brws %"
  output = ""

[[snippets]]
  description = "Generate private key (default size: 2048 so far)"
  command = "openssl genrsa > private-key.pem"
  output = ""

[[snippets]]
  description = "Generate public key with given private key"
  command = "openssl rsa -pubout < private-key.pem > public-key.pem"
  output = ""

[[snippets]]
  description = "Generate CSR (Certificate Signing Request) with given server private key"
  command = "openssl req -new -key server.key > server.csr"
  output = ""

[[snippets]]
  description = "Generate CRT (Self-signed certificate) with given server private key and self-signed CSR"
  command = "openssl x509 -req -signkey server.key < server.csr > server.crt"
  output = ""

[[snippets]]
  description = "Checkout remote master anyway"
  command = "git reset --hard origin/master"
  output = ""

[[snippets]]
  description = "Generate uuid with lower cases"
  command = "uuidgen | tr \"[:upper:]\" \"[:lower:]\""
  output = ""

[[snippets]]
  description = "Generate uuid with lower cases but without hyphen"
  command = "uuidgen | tr \"[:upper:]\" \"[:lower:]\" | tr -d \"-\""
  output = ""

[[snippets]]
  description = "Generate random hex with 4 bytes"
  command = "openssl rand -hex 4"
  output = ""

[[snippets]]
  description = "List open files listen to 8080 port"
  command = "lsof -n -P -i :8080"
  output = ""

[[snippets]]
  description = "Replace \"deprecated\" with \"new\" for all files in the current directory"
  command = "find ./ -type f -exec sed -i -e 's/deprecated/new/g' {} \\;"
  output = ""

[[snippets]]
  description = "Generate public key fingerprint (github is using md5)"
  command = "ssh-keygen -E md5 -lf ~/.ssh/id_rsa.pub"
  output = ""

[[snippets]]
  description = "Generate ssh key (algorithm:ecdsa, length:521)"
  command = "ssh-keygen -t ecdsa -b 521 -f ~/.ssh/id_rsa"
  output = ""

[[snippets]]
  description = "Generate ssh key (algorithm:ed25519, length:256)"
  command = "ssh-keygen -t ed25519 -f ~/.ssh/id_rsa"
  output = ""

[[snippets]]
  description = "Generate random password whose length is 30"
  command = "gpg --gen-random --armor 1 30"
  output = ""

[[snippets]]
  description = "npx install-peerdeps --dev eslint-config-airbnb"
  command = "Install eslint-config-airbnb"
  output = ""

[[snippets]]
  description = "git remote add origin https://github.com/koketani/some-repo.git"
  command = "Register remote url as origin"
  output = ""

[[snippets]]
  description = "nc -u -z 192.168.100.1 53"
  command = "Scan nameserver port (53 udp) on given server"
  output = ""

[[snippets]]
  description = "Build plantuml files under the current directory"
  command = "java -DPLANTUML_LIMIT_SIZE=81920 -jar ~/Downloads/plantuml.1.2019.12.jar"
  output = ""

[[snippets]]
  description = "configure gcloud cluster credentials for kubectl command"
  command = "gcloud --project=[project-id] container clusters get-credentials [cluster-name] --region [region-name]"
  output = ""

[[snippets]]
  description = "run netshoot for the container network trouble"
  command = "docker run -it --net container:<container_name> nicolaka/netshoot"
  output = ""
