# ~/.config/sheldon/plugins.toml

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = """{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}"""
source = """
{{ hooks?.pre | nl }}{% for file in files %}source \"{{ file }}\"
{% endfor %}{{ hooks?.post | nl }}"""
PATH = 'export PATH="{{ dir }}:$PATH"'
path = 'path=( "{{ dir }}" $path )'
fpath = 'fpath=( "{{ dir }}" $fpath )'
nop = 'true'

[plugins.agkozak-zsh-prompt]
github = "agkozak/agkozak-zsh-prompt"
use = ["*.zsh"]
apply = ["source"]

[plugins.fzf]
github = "junegunn/fzf"
dir = "shell"
use = ["*.zsh"]
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath"]
dir = "src"
use = ["_clang-format", "_direnv", "_openssl", "_protoc"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.OMZL]
github = "ohmyzsh/ohmyzsh"
apply = ["defer"]
dir = "lib"
use = ["git.zsh"]

# [plugins.oh-my-zsh]
# github = "ohmyzsh/ohmyzsh"
# apply = ["defer"]
# use = ["{{ name }}.sh"]
[plugins.ohmyzsh-completions-docker]
github = "ohmyzsh/ohmyzsh"
apply = ["fpath"]
dir = "plugins/docker"
use = ["_docker"]

[plugins.ohmyzsh-completions-fd]
github = "ohmyzsh/ohmyzsh"
apply = ["fpath"]
dir = "plugins/fd"
use = ["_fd"]

[plugins.ohmyzsh-plugins-git]
github = "ohmyzsh/ohmyzsh"
apply = ["defer"]
dir = "plugins/git"
use = ["git.plugin.zsh"]

[plugins.ohmyzsh-completions-pass]
github = "ohmyzsh/ohmyzsh"
apply = ["fpath"]
dir = "plugins/pass"
use = ["_pass"]

[plugins.ohmyzsh-completions-rustc]
github = "ohmyzsh/ohmyzsh"
apply = ["fpath"]
dir = "plugins/rust"
use = ["_rustc"]

[plugins.ohmyzsh-completions-vagrant]
github = "ohmyzsh/ohmyzsh"
apply = ["fpath"]
dir = "plugins/vagrant"
use = ["_vagrant"]

[plugins.zchee-zsh-completions]
github = "zchee/zsh-completions"
apply = ["defer"]
use = ["zsh-completions.plugin.zsh"]

# just want to host for tmux
[plugins.tmux-paste]
github = "brennanfee/tmux-paste"
use = ["readme.md"]
apply = ["nop"]
