# ~/.config/sheldon/plugins.toml

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = """{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}"""
source = """
{{ hooks?.pre | nl }}{% for file in files %}source \"{{ file }}\"
{% endfor %}{{ hooks?.post | nl }}"""
PATH = 'export PATH="{{ dir }}:$PATH"'
path = 'path=( "{{ dir }}" $path )'
fpath = 'fpath=( "{{ dir }}" $fpath )'
nop = 'true'

[plugins.agkozak-zsh-prompt]
github = "agkozak/agkozak-zsh-prompt"
use = ["*.zsh"]
apply = ["source"]

[plugins.fzf]
github = "junegunn/fzf"
dir = "shell"
use = ["*.zsh"]
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]
use = ["zsh-completions.plugin.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
apply = ["defer"]
dir = "lib"
use = ["{git}.zsh"]

[plugins.ohmyzsh]
github = "ohmyzsh/ohmyzsh"
apply = ["defer"]
dir = "plugins"
use = ["{git,rust,zoxide}/*.plugin.zsh"]

[plugins.zchee-zsh-completions]
github = "zchee/zsh-completions"
apply = ["defer"]
use = ["zsh-completions.plugin.zsh"]

# just want to host for tmux
[plugins.tmux-paste]
github = "brennanfee/tmux-paste"
use = ["readme.md"]
apply = ["nop"]

# completions by nixpkgs won't work?
# https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/azure-cli/default.nix
[plugins.azure-cli]
github = "Azure/azure-cli"
branch = "dev"
use = ["az.completion"]
apply = ["defer"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"
